export enum ActionHistory {
  MANUTENCE_CREATED = 'MANUTENÇÃO CRIADA',
  MANUTENCE_DELETED = 'MANUTENÇÃO DELETADA',
  MANUTENCE_ACCEPTED = 'MANUTENÇÃO ACEITA',
  MANUTENCE_REJECTED = 'MANUTENÇÃO REJEITADA',
}
