export enum SpecialtyManutence {
  HIDRAULICA = 'HIDRAULICA',
  ELETRICA = 'ELETRICA',
  ESTRUTURAL = 'ESTRUTURAL',
  PISO = 'PISO',
  PINTURA = 'PINTURA',
  TELHADO = 'TELHADO',
  JARDINAGEM = 'JARDINAGEM',
  DEDETIZACAO = 'DEDETIZACAO',
  OUTROS = 'OUTROS',
}
