export const DEFAULT_PAGE_SIZE = 10;
export const NAME_LENGTH_ERROR = "NAME MUST CONTAIN AT LEAST 5 CHARACTERS AND MAXIMUM 55 CHARACTERS"
export const MESSAGE_LENGTH_ERROR = "MESSAGE MUST CONTAIN AT LEAST 5 CHARACTERS AND MAXIMUM 55 CHARACTERS"
export const EMAIL_LENGTH_ERROR = "EMAIL MUST CONTAIN AT LEAST 5 CHARACTERS AND MAXIMUM 55 CHARACTERS"
export const EMAIL_FORMAT_INVALID = "THE EMAIL FORMAT IS INVALID"
export const PASSWORD_LENGTH_ERROR = "PASSWORD MUST CONTAIN AT LEAST 5 CHARACTERS AND MAXIMUM 55 CHARACTERS"
export const TELEFONE_FORMAT_ERROR = "THE PHONE FORMAT IS INVALID"