export const DEFAULT_PAGE_SIZE = 10;
export const NAME_LENGTH_ERROR =
  'O NOME DEVE CONTER PELO MENOS 5 CARACTERES E NO MÁXIMO 55 CARACTERES';
export const MESSAGE_LENGTH_ERROR =
  'A MENSAGEM DEVE CONTER PELO MENOS 5 CARACTERES E NO MÁXIMO 55 CARACTERES';
export const EMAIL_LENGTH_ERROR =
  'O EMAIL DEVE CONTER PELO MENOS 5 CARACTERES E NO MÁXIMO 55 CARACTERES';
export const EMAIL_FORMAT_INVALID = 'O FORMATO DO EMAIL É INVÁLIDO';
export const PASSWORD_LENGTH_ERROR =
  'A SENHA DEVE CONTER PELO MENOS 5 CARACTERES E NO MÁXIMO 55 CARACTERES';
export const TELEFONE_FORMAT_ERROR = 'O FORMATO DO TELEFONE É INVÁLIDO';
